routes/web.php
<?php

use App\Http\Controllers\TopicsController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', app()->getLocale());

Route::group([
    'prefix' => '{language}',
    'where' => ['locale' => '[a-z]{2}'],
], function () {
    Route::get('/', function () {
        return view('homepage');
    })->name('homepage');

    Route::redirect('/topic', '/#seeTopic');
    Route::post('/topic', [TopicsController::class, 'store'])->name('topic-store');
    Route::get('/topic/{topic}', [TopicsController::class, 'show'])->name('topic-show');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

// require __DIR__ . '/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/homepage.blade.php
<x-guest-layout>
    <div class="relative text-center text-white w-full mx-auto overflow-x-hidden pb-4">
        <div class="absolute inset-x-0 top-0 flex justify-center">
            <div class="w-120 h-120 -m-64 bg-purple-800 rounded-3xl transform rotate-45"></div>
        </div>
        <div class="relative mt-24 mb-24 md:mb-36" dir="auto">
            <h2 class="text-2xl font-bold mb-4">{{ __('Main Title') }}</h2>
            <p class="w-44 mx-auto">
                {{ __('Main Description') }}</p>
        </div>
    </div>

    <div class="w-80 mx-auto my-16">
        <div
            class="grid ggrid-cols-1 grid-cols-2  text-purple-800 border-purple-200 text-center border-4 rounded-3xl overflow-hidden shadow">
            <a class="p-4 hover:bg-purple-100 border-e-2 border-purple-200" href="#createTopic">
                <h3 class="text-lg font-bold">{{ __('Create Topic') }}</h3>
            </a>
            <a class="p-4 hover:bg-purple-100" href="#seeTopic">
                <h3 class="text-lg font-bold">{{ __('See Topic') }}</h3>
            </a>
        </div>
    </div>

    <div class="flex flex-col gap-2 w-80 mx-auto my-16 text-center text-gray-700 text-sm">
        {{-- <p>No registration needed.</p>
        <p>No personal information collected.</p>
        <p>Comments are anonymous.</p>
        <p>Comments are hidden during commenting time.</p>
        <p>Comments appear in random order.</p>
        <p>Topics will be wiped after one week.</p> --}}
        {!! Str::markdown(__('Features')) !!}
        <div class="w-4 h-4 transform rotate-45 bg-purple-800 mx-auto my-8"></div>
        {!! Str::markdown(__('FLOSS')) !!}
    </div>

    <div x-cloak x-data="{
        checkModalVisibility() {
            this.trash1 = location.hash==='#createTopic';
            this.trash2 = location.hash==='#seeTopic';
        }
    }">
        {{-- Modal 1: create topic --}}
        <div class="fixed bg-gray-900 bg-opacity-50 inset-0 flex justify-center items-center"
            x-show.transition="location.hash==='#createTopic'" x-on:hashchange.window="checkModalVisibility()"
            x-init="location.hash==='#createTopic'">
            <div class="w-full h-full sm:h-auto flex flex-col justify-between sm:max-w-lg bg-white shadow-lg sm:border-2 sm:rounded-xl overflow-hidden"
                x-on:click.away="location.hash='#none'">
                <div class="flex justify-between items-center border-b px-4 py-3">
                    <h3>{{ __('Create a New Topic') }}</h3>
                    <div class="cursor-pointer" x-on:click="location.hash='#none'">
                        <svg class="w-10 h-10 hover:rotate-90 transform transition" fill="none" stroke="currentColor"
                            viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1"
                                d="M6 18L18 6M6 6l12 12">
                            </path>
                        </svg>
                    </div>
                </div>

                <form action="{{ route('topic-store', app()->getLocale()) }}" method="POST"
                    class="h-full flex flex-col justify-between">
                    @csrf
                    <div class="px-4 py-5 bg-white space-y-6 my-4">
                        <div>
                            <div>
                                <label for="title" class="block text-sm font-medium text-gray-700">
                                    {{ __('Title') }}
                                </label>
                                <input type="text" name="title" id="title" minlength="5" maxlength="80" required
                                    dir="auto"
                                    class="focus:ring-purple-500 focus:border-purple-500 block w-full rounded-md sm:text-sm border-gray-300"
                                    placeholder="{{ __('Title Input Placeholder') }}">
                                @error('title')
                                    <p class="mt-2 text-sm text-red-500">
                                        {{ $message }}
                                    </p>
                                @enderror
                            </div>
                        </div>

                        <div>
                            <label for="description" class="block text-sm font-medium text-gray-700">
                                {{ __('Description') }}
                            </label>
                            <div class="mt-1">
                                <textarea id="description" name="description" rows="3" maxlength="1000" dir="auto"
                                    class="shadow-sm focus:ring-purple-500 focus:border-purple-500 mt-1 block w-full sm:text-sm border border-gray-300 rounded-md"
                                    placeholder="{{ __('Description Input Placeholder') }}"></textarea>
                            </div>
                            @error('description')
                                <p class="mt-2 text-sm text-red-500">
                                    {{ $message }}
                                </p>
                            @enderror
                        </div>

                        <div class="grid grid-cols-3 gap-6">
                            <div class="col-span-3 sm:col-span-2">
                                <label for="duration" class="block text-sm font-medium text-gray-700">
                                    {{ __('Commenting Duration') }}
                                </label>
                                <div class="mt-1 flex rounded-md shadow-sm">
                                    <input type="number" name="duration" id="duration" min="1" max="48"
                                        class="focus:ring-purple-500 focus:border-purple-500 flex-1 block w-full rounded-none rounded-s-md sm:text-sm border-gray-300"
                                        placeholder="Some duration for this topic" value="24">
                                    <span
                                        class="inline-flex items-center px-3 rounded-e-md border border-s-0 border-gray-300 bg-gray-50 text-gray-500 text-sm">
                                        {{ __('Hours') }}
                                    </span>
                                </div>
                                @error('duration')
                                    <p class="mt-2 text-sm text-red-500">
                                        {{ $message }}
                                    </p>
                                @enderror
                            </div>
                        </div>
                    </div>

                    <div class="flex justify-between items-center px-4 py-3 bg-purple-100">
                        <div class="ps-4">{{-- MESSAGE --}}</div>
                        <button type="submit"
                            class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-purple-600 hover:bg-purple-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500">
                            {{ __('Save') }}
                        </button>
                    </div>
                </form>
            </div>
        </div>

        {{-- Modal 1: see topic --}}
        <div class="fixed bg-gray-900 bg-opacity-50 inset-0 flex justify-center items-center"
            x-show.transition="location.hash==='#seeTopic'" x-on:hashchange.window="checkModalVisibility()"
            x-init="location.hash==='#seeTopic'">
            <div class="w-full h-full sm:h-auto flex flex-col justify-between sm:max-w-lg bg-white shadow-lg sm:border-2 sm:rounded-xl overflow-hidden"
                x-data="{url:''}" x-on:click.away="location.hash='#none'">
                <div class="flex justify-between items-center border-b px-4 py-3">
                    <h3>{{ __('See a Topic') }}</h3>
                    <div class="cursor-pointer" x-on:click="location.hash='#none'">
                        <svg class="w-10 h-10 hover:rotate-90 transform transition" fill="none" stroke="currentColor"
                            viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1"
                                d="M6 18L18 6M6 6l12 12">
                            </path>
                        </svg>
                    </div>
                </div>

                <div class="px-4 py-5 bg-white space-y-6 my-4">
                    <div>
                        <div>
                            <label for="title" class="block text-sm font-medium text-gray-700">
                                {{ __('Topic Token') }}
                            </label>
                            <input type="text" name="token" id="token" minlength="16" maxlength="16" required
                                x-model="url" dir="auto"
                                class="focus:ring-purple-500 focus:border-purple-500 flex-1 block w-full rounded-md sm:text-sm border-gray-300"
                                placeholder="{{ __('Token Input Placeholder') }}">
                            @error('title')
                                <p class="mt-2 text-sm text-red-500">
                                    {{ $message }}
                                </p>
                            @enderror
                        </div>
                    </div>

                </div>

                <div class="flex justify-between items-center px-4 py-3 bg-purple-100">
                    <div class="ps-4">{{-- MESSAGE --}}</div>
                    <a :href="'/topic/'+url"
                        class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-purple-600 hover:bg-purple-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500">
                        {{ __('Show') }}
                    </a>
                </div>
            </div>
        </div>
</x-guest-layout>